# Generated by Django 3.2.9 on 2021-11-28 19:59

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20211128_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Arquivo foto'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('admin', 'Administrador BD'), ('gestor', 'Gestor WFW'), ('staff', 'Apoiador'), ('giver', 'Doadoar'), ('beneficiary', 'Beneficiario')], max_length=20, verbose_name='Tipo de Usuário'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Já existe um usuario com este username.'}, help_text='Valor requirido. Somente letras e dígitos.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Username'),
        ),
    ]
